### ISSUE TITLE
2.4 to 3 ... keep getting ccminer crash...

### ISSUE THREAD

**Issue by StartxPH** [nemosminer/NemosMiner#396]
Since updated to 2.45 and 3... keeps getting ccminer crash...
have to stay at 2.4.1 ...

**Comment by Nickfost** [comment]
Same

**Comment by MrPlusGH** [comment]
Any log, config or context info which would help us help you?

**Comment by Nickfost** [comment]
ccminer wont benchmark it just crashes. 
[miner.log](https://github.com/nemosminer/NemosMiner-v3.0-windows/files/1820970/miner.log)
[switching.log](https://github.com/nemosminer/NemosMiner-v3.0-windows/files/1820971/switching.log)

**Comment by Nickfost** [comment]
when i returned to my system today it had completely crashed

**Comment by MrPlusGH** [comment]
Could you try to remove OC ?

**Comment by nemosminer** [comment]
because im currently testing and using it on multiple rigs im not getting that error at all so the problem is on you...

**Comment by StartxPH** [comment]
Updated my driver to latest release and the crash goes away....

**Comment by nemosminer** [comment]
.... If you have Windows 7, 8, or 8.1, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395

CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

running multiple cards its recommended to increase Virtual Memory 64gb is optimal



Made For & Tested with 6x10603gb 6x1070 6x1070ti 6x1080ti (users have reported up to 12cards working have not tested myself) Some miners do not support more that 9 cards

thats why i closed the issue because there was no issue...  im always testing the master code so i know if that was a real promblem and i knew it was not as none of my rigs had that issue... it clearly states in ReadMe "Requires nvidia driver newer than 388"
