### ISSUE TITLE
Question: Plus and 24hr

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#417]
Can I use PLUS/24hr on nicehash pool? or Only those who have Plus and 24hr inline with the pool?

**Comment by nemosminer** [comment]
no sorry no plus calculation for nicehash as of yet..

**Comment by MrPlusGH** [comment]
Plus calculates best price as a calculation from Actual 24hr and current estimates. NH works totally different and instant prices are not estimate but actual prices. So NH does not need Plus due to its nature.
The only one thing that Plus could make with NH is spike resistance.
Have thoughts about that for the future...
