### ISSUE TITLE
Question: Update

### ISSUE THREAD

**Issue by yuizen** [nemosminer/NemosMiner#463]
Does the miner updates itself whenever there are changes made in the release? Or do I need to download again? How do I keep the benchmark whenever I downloaded newest version?

**Comment by tr1l3r** [comment]
You need to download again. I wish Nemo would make ut so that Nemos updates itself automatically when new stable version is released. As far as benchmarks are conserned, just copy Stats folder into the newly downloaded Nemos and you'll have all your benchmarks and pool stats. But Nemo has been changing miners on certain algos, so many of the old bemchmarks will not be usable, because the program ig going to use another miner for the same algo.

**Comment by nemosminer** [comment]
no it does not update itself..  i would suggest to use v2.5.2 until version v3.0 is released...

note v2.5.2 was only released 10 days ago...
