### ISSUE TITLE
possibility to disable other card than 0 

### ISSUE THREAD

**Issue by krzysztof-hellostudio** [nemosminer/NemosMiner#488]
Hey, is there any way we can implement disabling other card than 0? the id 0 card is not always the one driving the desktop :)

**Comment by nemosminer** [comment]
not at moment : )

**Comment by dealbreak3r** [comment]
krzysztof-hellostudio:  Not in the GUI, but you can if you edit the "\config\config.json" file.   Change
```
   "SelGPUCC":  "0,1",
    "SelGPUDSTM":  "0 1",
```
to suit your needs. For example, if you had 3 cards and you want to omit 1, then replace the numbers with 0 and 2. Just don't hit "SAVE" in the GUI otherwise it'll overwrite your settings.

I run multiple instances (different card types) and customize each config accordingly. works for me.

**Comment by krzysztof-hellostudio** [comment]
ah, sounds like good plan, thanks.
