### ISSUE TITLE
Add x16r for blazepool

### ISSUE THREAD

**Issue by MrPlusGH** [nemosminer/NemosMiner#499]
Add x16r in PoolAlgos.json for BlazePool

**Comment by gak45** [comment]
yes and no. Blaze is a smaller pool so x16r payout is very random from day to day. 

BUT zerg is not up front with their pool fee. They advertise "zero percent pool fee"... but I found using a .9 price penalty factor gets it into the land of reality. 

The sad part is even with this issue they are usually higher payout than others due to having more coins (and thus more chances of a random moon event). 

The real issue is zerg's protection is non-existent. Get on the wrong side of a fork and you will loose 6 hours of mining or more before he catches it and manually disables a coin. It is what happened yesterday... and many people are pissed off at pinpin who doesnt answer any questions and doesnt seem to care.

Do your own research and decide for yourself if zerg is right for you or not.

**Comment by Tesla74** [comment]
@gak45 
Zerg has changed fee to .5%.  Clear on homepage.  They said it was going to be temporary, but decided to make permanent.

**Comment by nemosminer** [comment]
done
