### ISSUE TITLE
ccminerCryptonight benchmark

### ISSUE THREAD

**Issue by Braintelligence** [nemosminer/NemosMiner#522]
![grafik](https://user-images.githubusercontent.com/6761196/38749688-ce0273d6-3f52-11e8-962a-82b14978b724.png)

**I wish...**

As you can see it does ~4000H/s and not ~416kH/s, verified by NiceHash:
![grafik](https://user-images.githubusercontent.com/6761196/38749726-ee41e398-3f52-11e8-910a-15a374075bd5.png)

Until this is fixed I need to deactivate this miner.

**Comment by OMGTAA** [comment]
Looks a syntax error maybe. Attached: 
![untitled](https://user-images.githubusercontent.com/37843297/38749873-bbeb74d4-3f18-11e8-87a6-0bff69dbaf1b.png)

**Comment by Braintelligence** [comment]
Is this related to localization issues? A decimal on a German system might be delimited by a comma rather than a dot for the OS.

**Comment by nemosminer** [comment]
thanks all my test rigs are not having this issue... tested on 6x1080ti and 6x1070ti rigs it shows correct speed... i will continue to test and see if i can replicate this so i can find cause of problem

**Comment by Braintelligence** [comment]
@nemosminer Could it be localization issues concerning the decimal delimiter?

**Comment by Renegade5399** [comment]
I am having the same issue as OMGTAA has in their screenshot. It won't benchmark because it is not seeing the hashrate. It's stopping at the word "accepted".

I'm also getting the weird text wrapping issue in the powershell window.

**Comment by NoKwarl** [comment]
I'm also having problems with this. ccminerCryptonight is reporting a zero hash rate after benchmarking. This is pretty serious - WhatToMine.com has cryptonightv7 in the lead (at least at nicehash for me) - any workaround ideas?

**Comment by NoKwarl** [comment]
Okay. Workaround: copied XMRig from Bin in an older NemosMiner, but I downloaded the latest version and replaced it. Updated the ps1 files for XMRig and ccminercryptonight to use XMRig for cryptonightv7. Finally, I changed the $_ argument for the -a command line option in the startxmr.ps1 to just say "cryptonight" because there is no "cryptonightv7" option in xmrig.

**Comment by nemosminer** [comment]
WhatToMine.com is wrong i  have never used it.. Its made for Noobs

cryptonightv7 already fully supported with XMRig you just need to remove # from cryptonightV7 but it only works with up2 3 cards... thats why i switched to ccminer-cryptonight

**Comment by nemosminer** [comment]
thanks i'll have a look into re writting the wrapper and include for wrapper 2moro see if i can fix this.. its still working fine on my test rigs with current code im testing with 8x10603gb / 6x1070ti / 6x1080ti

**Comment by nemosminer** [comment]
if you have 3 cards or less use XMRig instead of ccminercryptonight...

@scavern go into "miners" find XMRig.ps1

edit it :

remove #

eg. before
$Commands = [PSCustomObject]@{
#"cryptonight" = " --cuda-devices $SelGPUCC" #Cryptonight(max 3 gpus)
#"cryptonight-lite" = " --cuda-devices $SelGPUCC" #Cryptonight-lite(max 3 gpus)
#"cryptonightV7" = " --cuda-devices $SelGPUCC" #CryptonightV7(max 3 gpus)

eg. after
$Commands = [PSCustomObject]@{
"cryptonight" = " --cuda-devices $SelGPUCC" #Cryptonight(max 3 gpus)
#"cryptonight-lite" = " --cuda-devices $SelGPUCC" #Cryptonight-lite(max 3 gpus)
"cryptonightV7" = " --cuda-devices $SelGPUCC" #CryptonightV7(max 3 gpus)

save XMRig.ps1

you can then delete ccminercryptonight.ps1 from "miners" folder...

this will Enable XMRig it works well but only with up to 3 cards so you have a single 1070 so will work very well...

Hope this Helps you

Best Regards
Nemo

**Comment by nemosminer** [comment]
All fixed

**Comment by Braintelligence** [comment]
@nemosminer Awesome! Any ETA on a new release? =)

**Comment by Renegade5399** [comment]
You don't just download the most recent master? I just grab the latest version of Master once or twice a week, no need to wait for another official release as the Master here is already super stable.

**Comment by Braintelligence** [comment]
I only do that if the repo owner says it's safe to do so.
MPM for example is so unstable on master that you can't do that.

**Comment by Renegade5399** [comment]
Main reason I switched off MPM! I know the risks of using the master and that's fine. This project though, @nemosminer does a damn good job of having a stable Master.
