### ISSUE TITLE
bug detected

### ISSUE THREAD

**Issue by miner232** [nemosminer/NemosMiner#605]
i have been detected a bug
nemos miner recognize and shows that for example neoscrypt is more profitable then phi and yet mining phi the second most profitable algo please fix

**Comment by miner232** [comment]
also star pool isnt right many algos dont work and doesnt exisite there

**Comment by Braintelligence** [comment]
1. These are two different issues.
2. Nemosminer isn't automatically mining what's most profitable, but rather, depending on if you choose Plus mode or not, mining what will stay most profitable, foretold by several factors. What good would it do to switch to Neoscrypt for 1 minute, because profitability crashed that fast? You should read the Readme.

**Comment by miner232** [comment]
ok ty il check it out
and also check those pools like phi pool and star pool (mising algos cant connect)
you can close ty

**Comment by nemosminer** [comment]
no bug i know about phi pool star pool they are not my  my highest priority right now...
