### ISSUE TITLE
Miner not switching through benchmarking

### ISSUE THREAD

**Issue by Deeferdawg** [nemosminer/NemosMiner#702]
Installed new version and it is stuck on equihash and won't cycle through the benchmarking process

**Comment by thebeerbaron2018** [comment]
Check your miner PS1 file.... there were a couple of errors - you can see if this is the problem when you start the benchmark - maximise the miner window and see if it says in red something about API port and "127.0.0.1:" << note no port!  This is due to a typo in the miner where it says $Variables.MinerAPITCPPort  which is left over from 3.2 and if you've pulled the newer version it expects $Variables.NVIDIAMinerAPITCPPort  (please note it appears TWICE at the bottom of the miner file and needs to be changed in both places)

**Comment by Deeferdawg** [comment]
Ok, thanks. Really appreciate it...now I'm stuck on skunk with cryptodredge

**Comment by RickillerZ** [comment]
my config:
$Commands | Get-Member -MemberType NoteProperty | Select -ExpandProperty Name | ForEach {
    [PSCustomObject]@{
        Type = "NVIDIA"
        Path = $Path
        Arguments = "  -b 127.0.0.1:4444 -d $($Config.SelGPUCC) -a $_ --no-watchdog -o stratum+tcp://$($Pools.(Get-Algorithm($_)).Host):$($Pools.(Get-Algorithm($_)).Port) -u $($Pools.(Get-Algorithm($_)).User) -p $($Pools.(Get-Algorithm($_)).Pass)$($Commands.$_) -R 1 -q -N 1"
        HashRates = [PSCustomObject]@{(Get-Algorithm($_)) = $Stats."$($Name)_$(Get-Algorithm($_))_HashRate".Week * .99} # substract 1% devfee
        API = "cryptodredge"
        Port = "4444"
        Wrap = $false
        URI = $Uri
        User = $Pools.(Get-Algorithm($_)).User
    }
}

**Comment by Deeferdawg** [comment]
Awesome! Thanks so much!
