### ISSUE TITLE
 TimerUITick

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner#732]
Happening about once per day.

System.Management.Automation.CommandNotFoundException: The term 'TimerUITick' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at <ScriptBlock>(Closure , FunctionContext )
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeAsDelegateHelper(Object dollarUnder, Object dollarThis, Object[] args)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MrPlusGH** [comment]
First,
   It is the third time you do open an issue on the same topic.
   I replied on #731 saying i'll do my best to deal with the issue your facing.
   The issue being closed does not mean we do are not listening to you nor working on the problem.
   Please use #731 to track progress on this one.

Second,
   I guess you missed some part of my reply:
"Could you try the last version of NPlusMiner to see if you have the same behavior. I had no report of this on NPlusMiner. This part of code has been ported from NPlusMiner to NemosMiner. So it could help if you could confirm you have the same behavior on both."

Thanks for helping us help you.
MrPlus

**Comment by jagauthier** [comment]
There was misunderstanding on my very first issue [#730](https://github.com/nemosminer/NemosMiner/issues/730). When pasting it seems to have the critical pieces of information missing.   I'm not sure why, but I pasted a large amount of text and the actual error message was missing.  This was the original error message.

[#731](https://github.com/nemosminer/NemosMiner/issues/731) is a different error message.
'Enabled' Property vs 'TimerTickUI'.   They are not the same, so it's not the third time.  Please pay attention to the details!

I did see your reply about NPlusMiner but I can't just stop my life to try another piece of software, go through the whole benchmark process and edit every miner with that has a default intensity that is not compatible with my cards.  I'll get to it, but it's an **hours long** process.   I realize that is frustrating to you, as is tickets being closed without commentary is to people reporting the issue.

On that subject: That's not how a ticketing/issue system works.  Ticket should remain open until they are no longer relevant, and the issue should be used to track changes, updates, and information.

I will try NPlusMiner, but it's not an instantaneous thing I can do and report on.  

I will update this ticket with my results of NPlusMiner assuming it hasn't been closed.

**Comment by MrPlusGH** [comment]
My tone might have been the wrong one here. That was not intentional.
Don't read frustration, read interest and how the fuck are only very rare users see this behavior.
Don't get me wrong, user's experience is important and I want to get your problem fixed. Though i'm not able to reproduce so the only way to debug is to rely on you as other users are reporting this as fixed.

See #696 where a constructive approach helped make some progress on this very same problem. #731 and #730 are the same issue (related). Give the man some trust ;)

Again, i'm working on completely reviewing the code responsible for UI refresh which I think might fix it as the objects in your errors won't be used anymore.
This will take a bit of time (at least a couple days) as I'm sure you understand this is far from being a job and we all need to eat :)

About the Hours long process. If using NemosMiner3.3, all miners and stats files are compatible with NPLusMiner and can be copied across, that should make it a minutes long process. HTH

On another hand, thanks for the feedback on intensity settings. I have some work item in my queue to take these settings out of the miner file so it should be easier to manage and bring more compatibility with autoupdates in NPlusMiner. Stay tuned.

MrPlus

**Comment by jagauthier** [comment]
I pulled the source, and compared all my custom intensity settings.
I copied the stats over, and I am up and running with the same config.

I will report if the issue occurs again.. (it might take a couple days)

Pulling intensity out of source code control would be a huge win.
The current process of updating isn't as simple, as I have to do a pull into a different folder and then a source code comparison (winmerge) and move the differences.  

I can't read the error for 696, but if it's the same problem I can use that thread and post for updates.

**Comment by MrPlusGH** [comment]
@thebeerbaron2018, did you see any new occurence of the issue?

**Comment by thebeerbaron2018** [comment]
Unfortunately yes.  I've tried both Nemos and NPlus and the bug appears randomly on both still - although you last modifications greatly reduced the chances of it happening.  Unfortunately with the number of rigs I have and the fact they are at a remote location without remote access I can't have an unstable controlling program.  I've switched to multipoolminer for the moment - which has no GUI and doesn't exhibit the same issue.  I still have a bunch of rigs cordoned off for testing if you want me to test further.  At least others are having the same problem now though - so maybe we can get more data and figure it out.

**Comment by Olegik-ah** [comment]
Hello!
I have same issue with "Enabled" and "TimerTickUI".
My ticket [https://github.com/nemosminer/NemosMiner/issues/723](url) was closed without comments too.
I have 3 rigs running nemosminer. Noticed this feature - the more video cards the more often the error pops up...
Waiting for fixes. Thanks!

**Comment by Olegik-ah** [comment]
It will be great if Nemo will not close tickets until they are resolved. Or, at least write the reasons for closed tickets. Otherwise it looks very rude ... And it is not clear whether the work is being done or not

**Comment by nemosminer** [comment]
i create restart task in task scheduler to restart once every 24hours on all my rigs  to prevent crashes altho when i test new code i test with minimum or 6card rigs and always for over 48hours if your leaving your rigs running indefinitely ie, longer than a week straight you are bound to run it some crash... 
i did manage to reproduce this "TimerUITick" error  but that was old code the new master and v3.3 Release i have not been able to reproduce this "TimerUITick" 

Task Scheduler with restart every 24hour is personally recommend all my rigs run of ssd's so restart is less than 20sec downtime...

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner/issues/696

**Comment by Olegik-ah** [comment]
Now i use the newest source from master... The bug is still present. Rebooting rigs every 24 hours does not help with this error. I had about 5-7 errors. And 2-3 times the error occurred after 4-5 hours of script working.
It looks like threading error. When background thread trying to modify some properties of GUI thread without sync / invoke.
I once had a similar error in my .Net application. The error occurred periodically when trying to update datasource of DataGridView from background thread...

**Comment by nemosminer** [comment]
ok im testing source code atm on a few rigs all is well for me....
